title:Ming Li's Homepage
page-top-title:Ming Li
top-section-bg-text: Computer Science and communication
home-subtitle: Ming Li&ensp;|&ensp;李茗
copyright-text: '&copy; Ming Li 2023-2025. All Rights Reserved.'
